/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/Gaudi.gltf 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Gaudi = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./assets/Gaudi.gltf')
  const { actions, names } = useAnimations(animations, group)


  useEffect(() => {
    actions[names[0]].reset().fadeIn(1).play()
  }, [])

  console.log(names)

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Gaudi">
        <group name="Gaudi_1" rotation={[-Math.PI, 0, -Math.PI]}>
          <group name="DeformationSystem">
            <primitive object={nodes.Root_M} />
            <group name="FitSkeleton">
              <group name="Root" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                <group name="Chest" position={[-0.111, 0, 0]} rotation={[0, 0, -0.103]}>
                  <group name="Head" position={[-0.125, 0, 0]} rotation={[0, 0, -0.03]}>
                    <group name="HeadEnd" position={[-0.12, 0, 0]} />
                  </group>
                  <group name="Shoulder" position={[-0.06, -0.01, 0.085]} rotation={[-2.973, 0.943, 3.01]}>
                    <group name="Elbow" position={[-0.127, 0, 0]} rotation={[0, 0, -0.347]}>
                      <group name="Wrist" position={[-0.102, 0, 0]} rotation={[0.29, 0.114, -0.073]}>
                        <group name="Cup" position={[-0.01, -0.005, 0]} rotation={[0.102, 0.049, 0.043]}>
                          <group name="PinkyFinger1" position={[-0.039, -0.014, 0.01]} rotation={[-0.185, 0.317, 0.219]}>
                            <group name="PinkyFinger2" position={[-0.011, 0, 0]} rotation={[-0.115, 0.636, -0.178]}>
                              <group name="PinkyFinger3" position={[-0.008, 0, 0]} rotation={[-0.066, 0.117, -0.188]}>
                                <group name="PinkyFinger4" position={[-0.009, 0, 0]} />
                              </group>
                            </group>
                          </group>
                          <group name="RingFinger1" position={[-0.044, -0.007, 0.003]} rotation={[-0.151, 0.341, -0.013]}>
                            <group name="RingFinger2" position={[-0.016, 0, 0]} rotation={[-0.033, 0.25, 0.074]}>
                              <group name="RingFinger3" position={[-0.013, 0, 0]} rotation={[-0.055, 0.566, -0.126]}>
                                <group name="RingFinger4" position={[-0.009, 0, 0]} />
                              </group>
                            </group>
                          </group>
                        </group>
                        <group name="IndexFinger1" position={[-0.056, 0.012, 0.001]} rotation={[-0.031, -0.077, -0.103]}>
                          <group name="IndexFinger2" position={[-0.016, 0, 0]} rotation={[0.06, 0.425, 0.063]}>
                            <group name="IndexFinger3" position={[-0.015, 0, 0]} rotation={[0.064, 0.18, 0.081]}>
                              <group name="IndexFinger4" position={[-0.011, 0, 0]} />
                            </group>
                          </group>
                        </group>
                        <group name="MiddleFinger1" position={[-0.055, 0, 0]} rotation={[-0.013, 0.244, 0.059]}>
                          <group name="MiddleFinger2" position={[-0.016, 0, 0]} rotation={[-0.001, 0.256, 0]}>
                            <group name="MiddleFinger3" position={[-0.015, 0, 0]} rotation={[-0.001, 0.183, 0]}>
                              <group name="MiddleFinger4" position={[-0.014, 0, 0]} />
                            </group>
                          </group>
                        </group>
                        <group name="ThumbFinger1" position={[-0.01, 0.007, 0.005]} rotation={[1.001, -0.208, -0.612]}>
                          <group name="ThumbFinger2" position={[-0.025, 0, 0]} rotation={[0, 0.18, -0.186]}>
                            <group name="ThumbFinger3" position={[-0.017, 0, 0]} rotation={[-0.029, 0.153, 0.063]}>
                              <group name="ThumbFinger4" position={[-0.015, 0, 0]} />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Hip" position={[0.048, -0.005, 0.046]} rotation={[3.141, 0.022, -3.024]}>
                  <group name="Knee" position={[-0.212, 0, 0]} rotation={[0, 0, 0.065]}>
                    <group name="Ankle" position={[-0.199, 0, 0]} rotation={[-0.24, 0.04, -0.069]}>
                      <group name="Heel" position={[-0.041, -0.033, 0.002]} rotation={[1.81, 0.001, -Math.PI / 2]} />
                      <group name="Toes" position={[-0.031, 0.057, 0]} rotation={[0.055, -0.025, -1.385]}>
                        <group name="ToesEnd" position={[-0.039, 0, 0]} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group name="FaceGroup">
            <group name="FaceMotionSystem" position={[0, 0.74, -0.001]}>
              <group name="ConstrainedSetup" scale={9.118}>
                <group name="DeformJointConstraints" />
              </group>
              <group name="ControlsSetup">
                <group name="ctrlBoxOffset" position={[-0.064, 0.041, -0.044]}>
                  <group name="ctrlBox">
                    <group name="ctrlBoxLips_M" position={[0, -0.014, 0]} scale={5.482}>
                      <group name="ctrlLips_M" />
                    </group>
                  </group>
                </group>
                <group name="EyeControls">
                  <group name="EyeOffset_L" position={[-0.018, 0.053, -0.044]}>
                    <group name="EyeAim_L">
                      <group name="SDKEye_L">
                        <group name="Eye_L" />
                      </group>
                    </group>
                  </group>
                  <group name="EyeOffset_R" position={[0.018, 0.053, -0.044]}>
                    <group name="EyeAim_R">
                      <group name="SDKEye_R" rotation={[0.036, 0, 0]}>
                        <group name="Eye_R" />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="OnFacecontrols" scale={9.118}>
                  <group name="SideReverse_L">
                    <group name="CheekBoneOffset_L" position={[-0.003, 0.004, -0.005]} rotation={[0, 1.047, 0]}>
                      <group name="CheekBoneFollow_L">
                        <group name="SDKCheekBone_L">
                          <group name="CheekBone_L" />
                        </group>
                      </group>
                    </group>
                    <group name="CheekOffset_L" position={[-0.003, 0.003, -0.005]} rotation={[0, 1.05, 0]}>
                      <group name="CheekFollow_L">
                        <group name="SDKCheek_L">
                          <group name="Cheek_L" />
                        </group>
                      </group>
                    </group>
                    <group name="cornerLipOffset_L" position={[-0.002, 0.002, -0.006]} rotation={[0.003, 0.814, -0.002]}>
                      <group name="cornerLipAttach_L">
                        <group name="SDKcornerLip_L">
                          <group name="cornerLipSubtract_L">
                            <group name="cornerLip_L" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="EyeBrowMid2Offset_L" position={[-0.003, 0.008, -0.005]} rotation={[0, 0.891, 0]}>
                      <group name="EyeBrowMid2Follow_L">
                        <group name="SDKEyeBrowMid2_L">
                          <group name="EyeBrowMid2_L" />
                        </group>
                      </group>
                    </group>
                    <group name="EyeBrowRegionOffset_L" position={[-0.002, 0.007, -0.005]}>
                      <group name="SDKEyeBrowRegion_L">
                        <group name="EyeBrowRegion_L">
                          <group name="EyeBrowInnerOffset_L" position={[0.001, 0, -0.001]} rotation={[0, 0.312, 0]}>
                            <group name="SDKEyeBrowInner_L">
                              <group name="EyeBrowInner_L" />
                            </group>
                          </group>
                          <group name="EyeBrowOuterOffset_L" position={[-0.001, 0, 0.001]} rotation={[0, 1.179, 0]}>
                            <group name="SDKEyeBrowOuter_L">
                              <group name="EyeBrowOuter_L" />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="EyeRegionOffset_L" position={[-0.002, 0.006, -0.005]}>
                      <group name="SDKEyeRegion_L">
                        <group name="EyeRegion_L">
                          <group name="lowerLidOffset_L" position={[0, -0.001, -0.001]} rotation={[0, 0.057, 0]}>
                            <group name="lowerLidAttach_L">
                              <group name="lowerLidFleshy_L">
                                <group name="SDKlowerLid_L">
                                  <group name="lowerLidSubtract_L">
                                    <group name="lowerLid_L" />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="upperLidOffset_L" position={[0, 0.001, -0.001]} rotation={[0, 0.057, 0]}>
                            <group name="upperLidAttach_L">
                              <group name="upperLidFleshy_L">
                                <group name="SDKupperLid_L">
                                  <group name="upperLidSubtract_L">
                                    <group name="upperLid_L" />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="FrownBulgeOffset_L" position={[-0.002, 0.001, -0.005]} rotation={[0, 0.8, 0]}>
                      <group name="FrownBulgeFollow_L">
                        <group name="SDKFrownBulge_L">
                          <group name="FrownBulge_L" />
                        </group>
                      </group>
                    </group>
                    <group name="lowerLidOuterOffset_L" position={[-0.002, 0.005, -0.006]} rotation={[0, 0.057, 0]}>
                      <group name="SDKlowerLidOuter_L">
                        <group name="lowerLidOuter_L" />
                      </group>
                    </group>
                    <group name="lowerLipAOffset_L" position={[0, 0.001, -0.006]} rotation={[0, 0.288, 0]}>
                      <group name="lowerLipAAttach_L">
                        <group name="SDKlowerLipA_L">
                          <group name="lowerLipASubtract_L">
                            <group name="lowerLipA_L" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="lowerLipBOffset_L" position={[-0.001, 0.001, -0.006]} rotation={[0.004, 0.612, -0.002]}>
                      <group name="lowerLipBAttach_L">
                        <group name="SDKlowerLipB_L">
                          <group name="lowerLipBSubtract_L">
                            <group name="lowerLipB_L" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="lowerLipCOffset_L" position={[-0.001, 0.001, -0.006]} rotation={[0.006, 0.77, -0.004]}>
                      <group name="lowerLipCAttach_L">
                        <group name="SDKlowerLipC_L">
                          <group name="lowerLipCSubtract_L">
                            <group name="lowerLipC_L" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="SmileBulgeOffset_L" position={[-0.002, 0.002, -0.005]} rotation={[0, 0.824, 0]}>
                      <group name="SmileBulgeFollow_L">
                        <group name="SDKSmileBulge_L">
                          <group name="SmileBulge_L" />
                        </group>
                      </group>
                    </group>
                    <group name="upperLipAOffset_L" position={[0, 0.002, -0.006]} rotation={[0, 0.275, 0]}>
                      <group name="upperLipAAttach_L">
                        <group name="SDKupperLipA_L">
                          <group name="upperLipASubtract_L">
                            <group name="upperLipA_L" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="upperLipBOffset_L" position={[-0.001, 0.002, -0.006]} rotation={[-0.002, 0.602, 0.001]}>
                      <group name="upperLipBAttach_L">
                        <group name="SDKupperLipB_L">
                          <group name="upperLipBSubtract_L">
                            <group name="upperLipB_L" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="upperLipCOffset_L" position={[-0.001, 0.002, -0.006]} rotation={[-0.001, 0.768, 0.001]}>
                      <group name="upperLipCAttach_L">
                        <group name="SDKupperLipC_L">
                          <group name="upperLipCSubtract_L">
                            <group name="upperLipC_L" />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="SideReverse_M">
                    <group name="ChinCreaseOffset_M" position={[0, 0, -0.007]}>
                      <group name="ChinCreaseFollow_M">
                        <group name="SDKChinCrease_M">
                          <group name="ChinCrease_M" />
                        </group>
                      </group>
                    </group>
                    <group name="EyeBrowCenterOffset_M" position={[0, 0.008, -0.006]}>
                      <group name="EyeBrowCenterFollow_M">
                        <group name="SDKEyeBrowCenter_M">
                          <group name="EyeBrowCenter_M" />
                        </group>
                      </group>
                    </group>
                    <group name="JawOffset_M" position={[0, 0.005, -0.002]}>
                      <group name="SDKJaw_M">
                        <group name="Jaw_M" />
                      </group>
                    </group>
                    <group name="LipRegionOffset_M" position={[0, 0.002, -0.006]}>
                      <group name="SDKLipRegion_M">
                        <group name="LipRegion_M">
                          <group name="LipOffset_L" position={[-0.002, 0, 0.001]} rotation={[0.003, 0.814, -0.002]}>
                            <group name="LipFollow_L">
                              <group name="SDKLip_L">
                                <group name="Lip_L" />
                              </group>
                            </group>
                          </group>
                          <group name="LipOffset_R" position={[0.002, 0, 0.001]} rotation={[-3.139, 0.813, 3.14]} scale={[1, 1, -1]}>
                            <group name="LipFollow_R">
                              <group name="SDKLip_R">
                                <group name="Lip_R" />
                              </group>
                            </group>
                          </group>
                          <group name="lowerLipOffset_M">
                            <group name="lowerLipFollow_M">
                              <group name="SDKlowerLip_M">
                                <group name="lowerLip_M" />
                              </group>
                            </group>
                          </group>
                          <group name="upperLipOffset_M">
                            <group name="upperLipFollow_M">
                              <group name="SDKupperLip_M">
                                <group name="upperLip_M" />
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="lowerTeethOffset_M" position={[0, 0.001, -0.005]}>
                      <group name="lowerTeethFollow_M">
                        <group name="SDKlowerTeeth_M">
                          <group name="lowerTeeth_M" />
                        </group>
                      </group>
                    </group>
                    <group name="NoseCreaseOffset_M" position={[0, 0.006, -0.006]}>
                      <group name="SDKNoseCrease_M">
                        <group name="NoseCrease_M" />
                      </group>
                    </group>
                    <group name="NoseRegionOffset_M" position={[0, 0.003, -0.007]}>
                      <group name="SDKNoseRegion_M">
                        <group name="NoseRegion_M">
                          <group name="NoseBridgeOffset_M" position={[0, 0.003, 0.001]}>
                            <group name="SDKNoseBridge_M">
                              <group name="NoseBridge_M" />
                            </group>
                          </group>
                          <group name="NoseCornerOffset_L" position={[-0.001, 0, 0.001]} rotation={[0, 0.396, 0]}>
                            <group name="SDKNoseCorner_L">
                              <group name="NoseCorner_L" />
                            </group>
                          </group>
                          <group name="NoseCornerOffset_R" position={[0.001, 0, 0.001]} rotation={[-Math.PI, 0.396, -Math.PI]} scale={[1, 1, -1]}>
                            <group name="SDKNoseCorner_R">
                              <group name="NoseCorner_R" />
                            </group>
                          </group>
                          <group name="NoseOffset_M" position={[0, 0, -0.001]}>
                            <group name="SDKNose_M">
                              <group name="Nose_M" />
                            </group>
                          </group>
                          <group name="NoseSideOffset_L" position={[-0.001, 0.001, 0.001]} rotation={[0, 0.376, 0]}>
                            <group name="SDKNoseSide_L">
                              <group name="NoseSide_L" />
                            </group>
                          </group>
                          <group name="NoseSideOffset_R" position={[0.001, 0.001, 0.001]} rotation={[-Math.PI, 0.376, -Math.PI]} scale={[1, 1, -1]}>
                            <group name="SDKNoseSide_R">
                              <group name="NoseSide_R" />
                            </group>
                          </group>
                          <group name="NoseUnderOffset_M" position={[0, 0, 0]}>
                            <group name="SDKNoseUnder_M">
                              <group name="NoseUnder_M" />
                            </group>
                          </group>
                          <group name="NostrilOffset_L" position={[-0.001, 0, 0]} rotation={[0, 0.226, 0]}>
                            <group name="SDKNostril_L">
                              <group name="Nostril_L" />
                            </group>
                          </group>
                          <group name="NostrilOffset_R" position={[0.001, 0, 0]} rotation={[-Math.PI, 0.226, -Math.PI]} scale={[1, 1, -1]}>
                            <group name="SDKNostril_R">
                              <group name="Nostril_R" />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="Tongue0Offset_M" position={[0, 0.001, -0.003]} rotation={[0, -Math.PI / 2, 0]}>
                      <group name="Tongue0Follow_M">
                        <group name="SDKTongue0_M">
                          <group name="Tongue0_M">
                            <group name="Tongue1Offset_M" position={[-0.002, 0, 0]}>
                              <group name="SDKTongue1_M">
                                <group name="Tongue1_M">
                                  <group name="Tongue2Offset_M" position={[-0.002, 0, 0]}>
                                    <group name="SDKTongue2_M">
                                      <group name="Tongue2_M">
                                        <group name="Tongue3Offset_M" position={[-0.002, 0, 0]}>
                                          <group name="SDKTongue3_M">
                                            <group name="Tongue3_M" />
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="upperTeethOffset_M" position={[0, 0.002, -0.005]}>
                      <group name="SDKupperTeeth_M">
                        <group name="upperTeeth_M" />
                      </group>
                    </group>
                  </group>
                  <group name="SideReverse_R" scale={[-1, 1, 1]}>
                    <group name="CheekBoneOffset_R" position={[-0.003, 0.004, -0.005]} rotation={[0, 1.047, 0]}>
                      <group name="CheekBoneFollow_R">
                        <group name="SDKCheekBone_R">
                          <group name="CheekBone_R" />
                        </group>
                      </group>
                    </group>
                    <group name="CheekOffset_R" position={[-0.003, 0.003, -0.005]} rotation={[0, 1.05, 0]}>
                      <group name="CheekFollow_R">
                        <group name="SDKCheek_R">
                          <group name="Cheek_R" />
                        </group>
                      </group>
                    </group>
                    <group name="cornerLipOffset_R" position={[-0.002, 0.002, -0.006]} rotation={[0.003, 0.813, -0.002]}>
                      <group name="cornerLipAttach_R">
                        <group name="SDKcornerLip_R">
                          <group name="cornerLipSubtract_R">
                            <group name="cornerLip_R" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="EyeBrowMid2Offset_R" position={[-0.003, 0.008, -0.005]} rotation={[0, 0.891, 0]}>
                      <group name="EyeBrowMid2Follow_R">
                        <group name="SDKEyeBrowMid2_R">
                          <group name="EyeBrowMid2_R" />
                        </group>
                      </group>
                    </group>
                    <group name="EyeBrowRegionOffset_R" position={[-0.002, 0.007, -0.005]}>
                      <group name="SDKEyeBrowRegion_R">
                        <group name="EyeBrowRegion_R">
                          <group name="EyeBrowInnerOffset_R" position={[0.001, 0, -0.001]} rotation={[0, 0.312, 0]}>
                            <group name="SDKEyeBrowInner_R">
                              <group name="EyeBrowInner_R" />
                            </group>
                          </group>
                          <group name="EyeBrowOuterOffset_R" position={[-0.001, 0, 0.001]} rotation={[0, 1.179, 0]}>
                            <group name="SDKEyeBrowOuter_R">
                              <group name="EyeBrowOuter_R" />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="EyeRegionOffset_R" position={[-0.002, 0.006, -0.005]}>
                      <group name="SDKEyeRegion_R">
                        <group name="EyeRegion_R">
                          <group name="lowerLidOffset_R" position={[0, -0.001, -0.001]} rotation={[0, 0.057, 0]}>
                            <group name="lowerLidAttach_R">
                              <group name="lowerLidFleshy_R">
                                <group name="SDKlowerLid_R">
                                  <group name="lowerLidSubtract_R">
                                    <group name="lowerLid_R" />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="upperLidOffset_R" position={[0, 0.001, -0.001]} rotation={[0, 0.057, 0]}>
                            <group name="upperLidAttach_R">
                              <group name="upperLidFleshy_R">
                                <group name="SDKupperLid_R">
                                  <group name="upperLidSubtract_R">
                                    <group name="upperLid_R" />
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="FrownBulgeOffset_R" position={[-0.002, 0.001, -0.005]} rotation={[0, 0.8, 0]}>
                      <group name="FrownBulgeFollow_R">
                        <group name="SDKFrownBulge_R">
                          <group name="FrownBulge_R" />
                        </group>
                      </group>
                    </group>
                    <group name="lowerLidOuterOffset_R" position={[-0.002, 0.005, -0.006]} rotation={[0, 0.057, 0]}>
                      <group name="SDKlowerLidOuter_R">
                        <group name="lowerLidOuter_R" />
                      </group>
                    </group>
                    <group name="lowerLipAOffset_R" position={[0, 0.001, -0.006]} rotation={[0, 0.284, 0]}>
                      <group name="lowerLipAAttach_R">
                        <group name="SDKlowerLipA_R">
                          <group name="lowerLipASubtract_R">
                            <group name="lowerLipA_R" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="lowerLipBOffset_R" position={[-0.001, 0.001, -0.006]} rotation={[0.004, 0.609, -0.002]}>
                      <group name="lowerLipBAttach_R">
                        <group name="SDKlowerLipB_R">
                          <group name="lowerLipBSubtract_R">
                            <group name="lowerLipB_R" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="lowerLipCOffset_R" position={[-0.001, 0.001, -0.006]} rotation={[0.006, 0.768, -0.004]}>
                      <group name="lowerLipCAttach_R">
                        <group name="SDKlowerLipC_R">
                          <group name="lowerLipCSubtract_R">
                            <group name="lowerLipC_R" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="SmileBulgeOffset_R" position={[-0.002, 0.002, -0.005]} rotation={[0, 0.824, 0]}>
                      <group name="SmileBulgeFollow_R">
                        <group name="SDKSmileBulge_R">
                          <group name="SmileBulge_R" />
                        </group>
                      </group>
                    </group>
                    <group name="upperLipAOffset_R" position={[0, 0.002, -0.006]} rotation={[0, 0.271, 0]}>
                      <group name="upperLipAAttach_R">
                        <group name="SDKupperLipA_R">
                          <group name="upperLipASubtract_R">
                            <group name="upperLipA_R" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="upperLipBOffset_R" position={[-0.001, 0.002, -0.006]} rotation={[-0.002, 0.599, 0.001]}>
                      <group name="upperLipBAttach_R">
                        <group name="SDKupperLipB_R">
                          <group name="upperLipBSubtract_R">
                            <group name="upperLipB_R" />
                          </group>
                        </group>
                      </group>
                    </group>
                    <group name="upperLipCOffset_R" position={[-0.001, 0.002, -0.006]} rotation={[-0.001, 0.767, 0.001]}>
                      <group name="upperLipCAttach_R">
                        <group name="SDKupperLipC_R">
                          <group name="upperLipCSubtract_R">
                            <group name="upperLipC_R" />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group name="FaceDeformationSystem">
              <group name="LidSetup">
                <group name="LidSetup_L" position={[-0.018, 0.793, -0.045]} scale={9.118}>
                  <group name="lowerLidMain1Aim_L" rotation={[-Math.PI, -0.5, -2.764]} scale={0.11}>
                    <group name="lowerLidMain1AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain2Aim_L" rotation={[Math.PI, -0.824, -2.636]} scale={0.11}>
                    <group name="lowerLidMain2AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain3Aim_L" rotation={[-Math.PI, -1.405, -2.559]} scale={0.11}>
                    <group name="lowerLidMain3AimEnd_L" position={[-0.009, 0, 0]} />
                  </group>
                  <group name="lowerLidMain4Aim_L" rotation={[0, -1.155, 0.55]} scale={0.11}>
                    <group name="lowerLidMain4AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain5Aim_L" rotation={[0, -0.722, 0.457]} scale={0.11}>
                    <group name="lowerLidMain5AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain6Aim_L" rotation={[0, -0.392, 0.296]} scale={0.11}>
                    <group name="lowerLidMain6AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain7Aim_L" rotation={[0, -0.241, 0.121]} scale={0.11}>
                    <group name="lowerLidMain7AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain0Aim_L" rotation={[-Math.PI, -0.326, -2.888]} scale={0.11}>
                    <group name="upperLidMain0AimEnd_L" position={[-0.011, 0, 0]} />
                  </group>
                  <group name="upperLidMain1Aim_L" rotation={[Math.PI, -0.414, -3.12]} scale={0.11}>
                    <group name="upperLidMain1AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain2Aim_L" rotation={[Math.PI, -0.674, 2.844]} scale={0.11}>
                    <group name="upperLidMain2AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain3Aim_L" rotation={[Math.PI, -1.148, 2.63]} scale={0.11}>
                    <group name="upperLidMain3AimEnd_L" position={[-0.009, 0, 0]} />
                  </group>
                  <group name="upperLidMain4Aim_L" rotation={[0, -1.467, -0.57]} scale={0.11}>
                    <group name="upperLidMain4AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain5Aim_L" rotation={[0, -0.994, -0.525]} scale={0.11}>
                    <group name="upperLidMain5AimEnd_L" position={[-0.009, 0, 0]} />
                  </group>
                  <group name="upperLidMain6Aim_L" rotation={[0, -0.584, -0.382]} scale={0.11}>
                    <group name="upperLidMain6AimEnd_L" position={[-0.009, 0, 0]} />
                  </group>
                  <group name="upperLidMain7Aim_L" rotation={[0, -0.329, -0.189]} scale={0.11}>
                    <group name="upperLidMain7AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain8Aim_L" rotation={[0, -0.201, -0.027]} scale={0.11}>
                    <group name="upperLidMain8AimEnd_L" position={[-0.01, 0, 0]} />
                  </group>
                </group>
                <group name="LidSetup_R" position={[0.018, 0.793, -0.045]} rotation={[-Math.PI, 0, 0]} scale={[9.118, 9.118, -9.118]}>
                  <group name="lowerLidMain1Aim_R" rotation={[0, -0.498, -0.37]} scale={[0.11, 0.11, -0.11]}>
                    <group name="lowerLidMain1AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain2Aim_R" rotation={[0, -0.821, -0.495]} scale={[0.11, 0.11, -0.11]}>
                    <group name="lowerLidMain2AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain3Aim_R" rotation={[0, -1.401, -0.571]} scale={[0.11, 0.11, -0.11]}>
                    <group name="lowerLidMain3AimEnd_R" position={[-0.009, 0, 0]} />
                  </group>
                  <group name="lowerLidMain4Aim_R" rotation={[-Math.PI, -1.158, 2.603]} scale={[0.11, 0.11, -0.11]}>
                    <group name="lowerLidMain4AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain5Aim_R" rotation={[Math.PI, -0.724, 2.697]} scale={[0.11, 0.11, -0.11]}>
                    <group name="lowerLidMain5AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain6Aim_R" rotation={[Math.PI, -0.393, 2.856]} scale={[0.11, 0.11, -0.11]}>
                    <group name="lowerLidMain6AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="lowerLidMain7Aim_R" rotation={[-Math.PI, -0.242, 3.028]} scale={[0.11, 0.11, -0.11]}>
                    <group name="lowerLidMain7AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain0Aim_R" rotation={[0, -0.326, -0.249]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain0AimEnd_R" position={[-0.011, 0, 0]} />
                  </group>
                  <group name="upperLidMain1Aim_R" rotation={[0, -0.411, -0.008]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain1AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain2Aim_R" rotation={[0, -0.668, 0.321]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain2AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain3Aim_R" rotation={[0, -1.14, 0.537]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain3AimEnd_R" position={[-0.009, 0, 0]} />
                  </group>
                  <group name="upperLidMain4Aim_R" rotation={[Math.PI, -1.474, -2.546]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain4AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain5Aim_R" rotation={[-Math.PI, -1, -2.591]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain5AimEnd_R" position={[-0.009, 0, 0]} />
                  </group>
                  <group name="upperLidMain6Aim_R" rotation={[Math.PI, -0.588, -2.738]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain6AimEnd_R" position={[-0.009, 0, 0]} />
                  </group>
                  <group name="upperLidMain7Aim_R" rotation={[-Math.PI, -0.332, -2.94]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain7AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                  <group name="upperLidMain8Aim_R" rotation={[Math.PI, -0.201, -3.11]} scale={[0.11, 0.11, -0.11]}>
                    <group name="upperLidMain8AimEnd_R" position={[-0.01, 0, 0]} />
                  </group>
                </group>
              </group>
              <group name="LipSetup">
                <group name="LipFollowHead" position={[0, 0.74, -0.001]} rotation={[-1.597, Math.PI / 2, 0]}>
                  <group name="LipFollicles" position={[-0.015, 0.06, 0]} rotation={[Math.PI / 2, 0.026, Math.PI / 2]}>
                    <group name="lowerfollicle0_M" position={[0, 0.001, 0.001]} />
                    <group name="lowerfollicle1_L" position={[-0.005, 0.001, 0.002]} rotation={[0, 0.28, 0]} />
                    <group name="lowerfollicle1_R" position={[0.005, 0.001, 0.002]} rotation={[0, -0.28, 0]} />
                    <group name="lowerfollicle2_L" position={[-0.01, 0.001, 0.004]} rotation={[0, 0.629, 0]} />
                    <group name="lowerfollicle2_R" position={[0.01, 0.001, 0.004]} rotation={[0, -0.629, 0]} />
                    <group name="lowerfollicle3_L" position={[-0.012, 0.001, 0.007]} rotation={[0, 0.865, 0]} />
                    <group name="lowerfollicle3_R" position={[0.012, 0.001, 0.007]} rotation={[0, -0.865, 0]} />
                    <group name="lowerfollicle4_L" position={[-0.013, 0.001, 0.008]} rotation={[0, 0.903, 0]} />
                    <group name="lowerfollicle4_R" position={[0.013, 0.001, 0.008]} rotation={[0, -0.903, 0]} />
                    <group name="lowerfollicle5_L" position={[-0.014, 0.001, 0.009]} rotation={[0, 0.897, 0]} />
                    <group name="lowerfollicle5_R" position={[0.014, 0.001, 0.009]} rotation={[0, -0.897, 0]} />
                    <group name="upperfollicle0_M" position={[0, 0.001, 0.001]} />
                    <group name="upperfollicle1_L" position={[-0.004, 0.001, 0.002]} rotation={[0, 0.235, 0]} />
                    <group name="upperfollicle1_R" position={[0.004, 0.001, 0.002]} rotation={[0, -0.235, 0]} />
                    <group name="upperfollicle2_L" position={[-0.009, 0.001, 0.004]} rotation={[0, 0.503, 0]} />
                    <group name="upperfollicle2_R" position={[0.009, 0.001, 0.004]} rotation={[0, -0.503, 0]} />
                    <group name="upperfollicle3_L" position={[-0.012, 0.001, 0.006]} rotation={[0, 0.828, 0]} />
                    <group name="upperfollicle3_R" position={[0.012, 0.001, 0.006]} rotation={[0, -0.828, 0]} />
                    <group name="upperfollicle4_L" position={[-0.013, 0.001, 0.008]} rotation={[0, 0.902, 0]} />
                    <group name="upperfollicle4_R" position={[0.013, 0.001, 0.008]} rotation={[0, -0.902, 0]} />
                    <group name="upperfollicle5_L" position={[-0.014, 0.001, 0.009]} rotation={[0, 0.896, 0]} />
                    <group name="upperfollicle5_R" position={[0.014, 0.001, 0.009]} rotation={[0, -0.896, 0]} />
                    <group name="upperfollicle6_L" position={[-0.014, 0.001, 0.009]} rotation={[0, 0.891, 0]} />
                    <group name="upperfollicle6_R" position={[0.014, 0.001, 0.009]} rotation={[0, -0.891, 0]} />
                  </group>
                  <group name="LipRibbonJoints" position={[0.74, 0.018, 0]} rotation={[Math.PI / 2, 0.026, Math.PI / 2]}>
                    <group name="cornerLipRibbonJointOffset_L" position={[-0.014, 0.754, -0.052]} rotation={[0.003, 0.814, -0.002]} scale={9.118}>
                      <group name="cornerLipRibbonJoint_L" />
                    </group>
                    <group name="cornerLipRibbonJointOffset_R" position={[0.014, 0.754, -0.052]} rotation={[-3.139, 0.813, 3.14]} scale={[9.118, 9.118, -9.118]}>
                      <group name="cornerLipRibbonJoint_R" />
                    </group>
                    <group name="lowerLipARibbonJointOffset_L" position={[-0.003, 0.753, -0.059]} rotation={[0, 0.288, 0]} scale={9.118}>
                      <group name="lowerLipARibbonJoint_L" />
                    </group>
                    <group name="lowerLipARibbonJointOffset_R" position={[0.003, 0.753, -0.059]} rotation={[-Math.PI, 0.284, -Math.PI]} scale={[9.118, 9.118, -9.118]}>
                      <group name="lowerLipARibbonJoint_R" />
                    </group>
                    <group name="lowerLipBRibbonJointOffset_L" position={[-0.01, 0.753, -0.057]} rotation={[0.004, 0.612, -0.002]} scale={9.118}>
                      <group name="lowerLipBRibbonJoint_L" />
                    </group>
                    <group name="lowerLipBRibbonJointOffset_R" position={[0.01, 0.753, -0.057]} rotation={[-3.138, 0.609, 3.139]} scale={[9.118, 9.118, -9.118]}>
                      <group name="lowerLipBRibbonJoint_R" />
                    </group>
                    <group name="lowerLipCRibbonJointOffset_L" position={[-0.013, 0.753, -0.054]} rotation={[0.006, 0.77, -0.004]} scale={9.118}>
                      <group name="lowerLipCRibbonJoint_L" />
                    </group>
                    <group name="lowerLipCRibbonJointOffset_R" position={[0.013, 0.753, -0.054]} rotation={[-3.135, 0.768, 3.137]} scale={[9.118, 9.118, -9.118]}>
                      <group name="lowerLipCRibbonJoint_R" />
                    </group>
                    <group name="upperLipARibbonJointOffset_L" position={[-0.003, 0.755, -0.06]} rotation={[0, 0.275, 0]} scale={9.118}>
                      <group name="upperLipARibbonJoint_L" />
                    </group>
                    <group name="upperLipARibbonJointOffset_R" position={[0.003, 0.755, -0.06]} rotation={[-Math.PI, 0.271, -Math.PI]} scale={[9.118, 9.118, -9.118]}>
                      <group name="upperLipARibbonJoint_R" />
                    </group>
                    <group name="upperLipBRibbonJointOffset_L" position={[-0.01, 0.754, -0.057]} rotation={[-0.002, 0.602, 0.001]} scale={9.118}>
                      <group name="upperLipBRibbonJoint_L" />
                    </group>
                    <group name="upperLipBRibbonJointOffset_R" position={[0.009, 0.754, -0.057]} rotation={[3.14, 0.599, -3.141]} scale={[9.118, 9.118, -9.118]}>
                      <group name="upperLipBRibbonJoint_R" />
                    </group>
                    <group name="upperLipCRibbonJointOffset_L" position={[-0.013, 0.754, -0.054]} rotation={[-0.001, 0.768, 0.001]} scale={9.118}>
                      <group name="upperLipCRibbonJoint_L" />
                    </group>
                    <group name="upperLipCRibbonJointOffset_R" position={[0.013, 0.754, -0.054]} rotation={[3.14, 0.767, -3.141]} scale={[9.118, 9.118, -9.118]}>
                      <group name="upperLipCRibbonJoint_R" />
                    </group>
                  </group>
                </group>
                <group name="LipRibbon">
                  <group name="lowerLipRibbon" />
                  <group name="upperLipRibbon" />
                </group>
              </group>
            </group>
          </group>
          <group name="Geometry">
            <group name="geo">
              <skinnedMesh name="Bear" geometry={nodes.Bear.geometry} material={materials.Gaudi} skeleton={nodes.Bear.skeleton} />
              <skinnedMesh name="EL" geometry={nodes.EL.geometry} material={materials.Gaudi} skeleton={nodes.EL.skeleton} />
              <skinnedMesh name="ER" geometry={nodes.ER.geometry} material={materials.Gaudi} skeleton={nodes.ER.skeleton} />
              <skinnedMesh name="Eyebrow_L" geometry={nodes.Eyebrow_L.geometry} material={materials.Gaudi} skeleton={nodes.Eyebrow_L.skeleton} />
              <skinnedMesh name="Eyebrow_R" geometry={nodes.Eyebrow_R.geometry} material={materials.Gaudi} skeleton={nodes.Eyebrow_R.skeleton} />
              <skinnedMesh name="Hair" geometry={nodes.Hair.geometry} material={materials.Gaudi} skeleton={nodes.Hair.skeleton} />
              <skinnedMesh name="Hat" geometry={nodes.Hat.geometry} material={materials.Gaudi} skeleton={nodes.Hat.skeleton} />
              <skinnedMesh name="Shirt1" geometry={nodes.Shirt1.geometry} material={materials.Gaudi} skeleton={nodes.Shirt1.skeleton} />
              <skinnedMesh name="Teeth_Inf" geometry={nodes.Teeth_Inf.geometry} material={materials.Gaudi} skeleton={nodes.Teeth_Inf.skeleton} />
              <skinnedMesh name="Teeth_Sup" geometry={nodes.Teeth_Sup.geometry} material={materials.Gaudi} skeleton={nodes.Teeth_Sup.skeleton} />
              <skinnedMesh name="Tongue" geometry={nodes.Tongue.geometry} material={materials.Gaudi} skeleton={nodes.Tongue.skeleton} />
              <skinnedMesh name="Body1" geometry={nodes.Body1.geometry} material={materials.Gaudi} skeleton={nodes.Body1.skeleton} />
            </group>
          </group>
          <group name="MotionSystem">
            <group name="FKIKSystem">
              <group name="FKIKParentConstraintArm_L" position={[0, 0.614, -0.002]} rotation={[-1.567, 1.571, 0]}>
                <group name="FKIKArm_L" position={[-0.063, -0.014, -0.153]} rotation={[Math.PI / 2, -0.003, Math.PI / 2]} />
              </group>
              <group name="FKIKParentConstraintArm_R" position={[0, 0.614, -0.002]} rotation={[-1.567, 1.571, 0]}>
                <group name="FKIKArm_R" position={[-0.063, -0.014, 0.153]} rotation={[Math.PI / 2, -0.003, Math.PI / 2]} />
              </group>
              <group name="FKIKParentConstraintLeg_L" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                <group name="FKIKLeg_L" position={[0.1, -0.012, -0.1]} rotation={[Math.PI / 2, -0.106, Math.PI / 2]} />
              </group>
              <group name="FKIKParentConstraintLeg_R" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                <group name="FKIKLeg_R" position={[0.1, -0.012, 0.1]} rotation={[Math.PI / 2, -0.106, Math.PI / 2]} />
              </group>
              <group name="FKIKParentConstraintSpine_M" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                <group name="FKIKSpine_M" position={[-0.053, 0, -0.094]} rotation={[Math.PI / 2, -0.106, Math.PI / 2]} />
              </group>
            </group>
            <group name="FKSystem">
              <group name="FKOffsetRoot_M" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                <group name="FKXRoot_M">
                  <group name="FKOffsetRootPart1_M" position={[-0.037, 0, 0]}>
                    <group name="FKInbetweenRootPart1_M">
                      <group name="FKExtraRootPart1_M">
                        <group name="FKRootPart1_M">
                          <group name="FKXRootPart1_M">
                            <group name="FKOffsetRootPart2_M" position={[-0.037, 0, 0]}>
                              <group name="FKInbetweenRootPart2_M">
                                <group name="FKExtraRootPart2_M">
                                  <group name="FKRootPart2_M">
                                    <group name="FKXRootPart2_M">
                                      <group name="FKOffsetChest_M" position={[-0.037, 0, 0]} rotation={[0, 0, -0.103]}>
                                        <group name="FKExtraChest_M">
                                          <group name="FKChest_M">
                                            <group name="FKXChest_M" />
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKExtraRoot_M">
                  <group name="FKRoot_M">
                    <group name="InbetweenTargetRoot_M" />
                  </group>
                </group>
                <group name="InbetweenRoot_M">
                  <group name="InbetweenRootPart0_M" />
                </group>
              </group>
              <group name="FKParentConstraintToChest_M" position={[0, 0.614, -0.002]} rotation={[-1.567, 1.571, 0]}>
                <group name="FKOffsetHead_M" position={[-0.125, 0, 0]} rotation={[0, 0, -0.03]}>
                  <group name="FKGlobalStaticHead_M">
                    <group name="FKGlobalHead_M">
                      <group name="FKExtraHead_M">
                        <group name="FKHead_M">
                          <group name="FKXHead_M" />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetShoulder_L" position={[-0.06, -0.01, -0.085]} rotation={[2.973, -0.943, -0.131]}>
                  <group name="FKExtraShoulder_L">
                    <group name="FKShoulder_L">
                      <group name="FKXShoulder_L">
                        <group name="FKOffsetElbow_L" position={[0.127, 0, 0]} rotation={[0, 0, -0.347]}>
                          <group name="FKExtraElbow_L">
                            <group name="FKElbow_L">
                              <group name="FKXElbow_L">
                                <group name="FKOffsetWrist_L" position={[0.102, 0, 0]} rotation={[0.29, 0.114, -0.073]}>
                                  <group name="FKExtraWrist_L">
                                    <group name="FKWrist_L">
                                      <group name="FKXWrist_L" />
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetShoulder_R" position={[-0.06, -0.01, 0.085]} rotation={[-2.973, 0.943, 3.01]}>
                  <group name="FKExtraShoulder_R">
                    <group name="FKShoulder_R">
                      <group name="FKXShoulder_R">
                        <group name="FKOffsetElbow_R" position={[-0.127, 0, 0]} rotation={[0, 0, -0.347]}>
                          <group name="FKExtraElbow_R">
                            <group name="FKElbow_R">
                              <group name="FKXElbow_R">
                                <group name="FKOffsetWrist_R" position={[-0.102, 0, 0]} rotation={[0.29, 0.114, -0.073]}>
                                  <group name="FKExtraWrist_R">
                                    <group name="FKWrist_R">
                                      <group name="FKXWrist_R" />
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="FKParentConstraintToRoot_M" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                <group name="FKOffsetHip_L" position={[0.048, -0.005, -0.046]} rotation={[-3.141, -0.022, 0.117]}>
                  <group name="FKExtraHip_L">
                    <group name="FKHip_L">
                      <group name="FKXHip_L">
                        <group name="FKOffsetKnee_L" position={[0.212, 0, 0]} rotation={[0, 0, 0.065]}>
                          <group name="FKExtraKnee_L">
                            <group name="FKKnee_L">
                              <group name="FKXKnee_L">
                                <group name="FKOffsetAnkle_L" position={[0.199, 0, 0]} rotation={[-0.24, 0.04, -0.069]}>
                                  <group name="FKExtraAnkle_L">
                                    <group name="FKAnkle_L">
                                      <group name="FKXAnkle_L">
                                        <group name="FKOffsetToes_L" position={[0.031, -0.057, 0]} rotation={[0.055, -0.025, -1.385]}>
                                          <group name="FKExtraToes_L">
                                            <group name="FKToes_L">
                                              <group name="FKXToes_L" />
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetHip_R" position={[0.048, -0.005, 0.046]} rotation={[3.141, 0.022, -3.024]}>
                  <group name="FKExtraHip_R">
                    <group name="FKHip_R">
                      <group name="FKXHip_R">
                        <group name="FKOffsetKnee_R" position={[-0.212, 0, 0]} rotation={[0, 0, 0.065]}>
                          <group name="FKExtraKnee_R">
                            <group name="FKKnee_R">
                              <group name="FKXKnee_R">
                                <group name="FKOffsetAnkle_R" position={[-0.199, 0, 0]} rotation={[-0.24, 0.04, -0.069]}>
                                  <group name="FKExtraAnkle_R">
                                    <group name="FKAnkle_R">
                                      <group name="FKXAnkle_R">
                                        <group name="FKOffsetToes_R" position={[-0.031, 0.057, 0]} rotation={[0.055, -0.025, -1.385]}>
                                          <group name="FKExtraToes_R">
                                            <group name="FKToes_R">
                                              <group name="FKXToes_R" />
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="FKParentConstraintToWrist_L" position={[-0.269, 0.547, -0.025]} rotation={[-1.828, -0.617, 2.592]}>
                <group name="FKOffsetCup_L" position={[0.01, 0.005, 0]} rotation={[0.102, 0.049, 0.043]}>
                  <group name="SDKFKCup_L">
                    <group name="FKExtraCup_L">
                      <group name="FKCup_L">
                        <group name="FKXCup_L">
                          <group name="FKOffsetPinkyFinger1_L" position={[0.039, 0.014, -0.01]} rotation={[-0.185, 0.317, 0.219]}>
                            <group name="SDKFKPinkyFinger1_L">
                              <group name="FKExtraPinkyFinger1_L">
                                <group name="FKPinkyFinger1_L">
                                  <group name="FKXPinkyFinger1_L">
                                    <group name="FKOffsetPinkyFinger2_L" position={[0.011, 0, 0]} rotation={[-0.115, 0.636, -0.178]}>
                                      <group name="SDKFKPinkyFinger2_L">
                                        <group name="FKExtraPinkyFinger2_L">
                                          <group name="FKPinkyFinger2_L">
                                            <group name="FKXPinkyFinger2_L">
                                              <group name="FKOffsetPinkyFinger3_L" position={[0.008, 0, 0]} rotation={[-0.066, 0.117, -0.188]}>
                                                <group name="SDKFKPinkyFinger3_L">
                                                  <group name="FKExtraPinkyFinger3_L">
                                                    <group name="FKPinkyFinger3_L">
                                                      <group name="FKXPinkyFinger3_L" />
                                                    </group>
                                                  </group>
                                                </group>
                                              </group>
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="FKOffsetRingFinger1_L" position={[0.044, 0.007, -0.003]} rotation={[-0.151, 0.341, -0.013]}>
                            <group name="SDKFKRingFinger1_L">
                              <group name="FKExtraRingFinger1_L">
                                <group name="FKRingFinger1_L">
                                  <group name="FKXRingFinger1_L">
                                    <group name="FKOffsetRingFinger2_L" position={[0.016, 0, 0]} rotation={[-0.033, 0.25, 0.074]}>
                                      <group name="SDKFKRingFinger2_L">
                                        <group name="FKExtraRingFinger2_L">
                                          <group name="FKRingFinger2_L">
                                            <group name="FKXRingFinger2_L">
                                              <group name="FKOffsetRingFinger3_L" position={[0.013, 0, 0]} rotation={[-0.055, 0.566, -0.126]}>
                                                <group name="SDKFKRingFinger3_L">
                                                  <group name="FKExtraRingFinger3_L">
                                                    <group name="FKRingFinger3_L">
                                                      <group name="FKXRingFinger3_L" />
                                                    </group>
                                                  </group>
                                                </group>
                                              </group>
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetIndexFinger1_L" position={[0.056, -0.012, -0.001]} rotation={[-0.031, -0.077, -0.103]}>
                  <group name="SDKFKIndexFinger1_L">
                    <group name="FKExtraIndexFinger1_L">
                      <group name="FKIndexFinger1_L">
                        <group name="FKXIndexFinger1_L">
                          <group name="FKOffsetIndexFinger2_L" position={[0.016, 0, 0]} rotation={[0.06, 0.425, 0.063]}>
                            <group name="SDKFKIndexFinger2_L">
                              <group name="FKExtraIndexFinger2_L">
                                <group name="FKIndexFinger2_L">
                                  <group name="FKXIndexFinger2_L">
                                    <group name="FKOffsetIndexFinger3_L" position={[0.015, 0, 0]} rotation={[0.064, 0.18, 0.081]}>
                                      <group name="SDKFKIndexFinger3_L">
                                        <group name="FKExtraIndexFinger3_L">
                                          <group name="FKIndexFinger3_L">
                                            <group name="FKXIndexFinger3_L" />
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetMiddleFinger1_L" position={[0.055, 0, 0]} rotation={[-0.013, 0.244, 0.059]}>
                  <group name="SDKFKMiddleFinger1_L">
                    <group name="FKExtraMiddleFinger1_L">
                      <group name="FKMiddleFinger1_L">
                        <group name="FKXMiddleFinger1_L">
                          <group name="FKOffsetMiddleFinger2_L" position={[0.016, 0, 0]} rotation={[-0.001, 0.256, 0]}>
                            <group name="SDKFKMiddleFinger2_L">
                              <group name="FKExtraMiddleFinger2_L">
                                <group name="FKMiddleFinger2_L">
                                  <group name="FKXMiddleFinger2_L">
                                    <group name="FKOffsetMiddleFinger3_L" position={[0.015, 0, 0]} rotation={[-0.001, 0.183, 0]}>
                                      <group name="SDKFKMiddleFinger3_L">
                                        <group name="FKExtraMiddleFinger3_L">
                                          <group name="FKMiddleFinger3_L">
                                            <group name="FKXMiddleFinger3_L" />
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetThumbFinger1_L" position={[0.01, -0.007, -0.005]} rotation={[1.001, -0.208, -0.612]}>
                  <group name="FKExtraThumbFinger1_L">
                    <group name="FKThumbFinger1_L">
                      <group name="FKXThumbFinger1_L">
                        <group name="FKOffsetThumbFinger2_L" position={[0.025, 0, 0]} rotation={[0, 0.18, -0.186]}>
                          <group name="SDKFKThumbFinger2_L">
                            <group name="FKExtraThumbFinger2_L">
                              <group name="FKThumbFinger2_L">
                                <group name="FKXThumbFinger2_L">
                                  <group name="FKOffsetThumbFinger3_L" position={[0.017, 0, 0]} rotation={[-0.029, 0.153, 0.063]}>
                                    <group name="SDKFKThumbFinger3_L">
                                      <group name="FKExtraThumbFinger3_L">
                                        <group name="FKThumbFinger3_L">
                                          <group name="FKXThumbFinger3_L" />
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="FKParentConstraintToWrist_R" position={[0.269, 0.547, -0.025]} rotation={[1.313, -0.617, 2.592]}>
                <group name="FKOffsetCup_R" position={[-0.01, -0.005, 0]} rotation={[0.102, 0.049, 0.043]}>
                  <group name="SDKFKCup_R">
                    <group name="FKExtraCup_R">
                      <group name="FKCup_R">
                        <group name="FKXCup_R">
                          <group name="FKOffsetPinkyFinger1_R" position={[-0.039, -0.014, 0.01]} rotation={[-0.185, 0.317, 0.219]}>
                            <group name="SDKFKPinkyFinger1_R">
                              <group name="FKExtraPinkyFinger1_R">
                                <group name="FKPinkyFinger1_R">
                                  <group name="FKXPinkyFinger1_R">
                                    <group name="FKOffsetPinkyFinger2_R" position={[-0.011, 0, 0]} rotation={[-0.115, 0.636, -0.178]}>
                                      <group name="SDKFKPinkyFinger2_R">
                                        <group name="FKExtraPinkyFinger2_R">
                                          <group name="FKPinkyFinger2_R">
                                            <group name="FKXPinkyFinger2_R">
                                              <group name="FKOffsetPinkyFinger3_R" position={[-0.008, 0, 0]} rotation={[-0.066, 0.117, -0.188]}>
                                                <group name="SDKFKPinkyFinger3_R">
                                                  <group name="FKExtraPinkyFinger3_R">
                                                    <group name="FKPinkyFinger3_R">
                                                      <group name="FKXPinkyFinger3_R" />
                                                    </group>
                                                  </group>
                                                </group>
                                              </group>
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                          <group name="FKOffsetRingFinger1_R" position={[-0.044, -0.007, 0.003]} rotation={[-0.151, 0.341, -0.013]}>
                            <group name="SDKFKRingFinger1_R">
                              <group name="FKExtraRingFinger1_R">
                                <group name="FKRingFinger1_R">
                                  <group name="FKXRingFinger1_R">
                                    <group name="FKOffsetRingFinger2_R" position={[-0.016, 0, 0]} rotation={[-0.033, 0.25, 0.074]}>
                                      <group name="SDKFKRingFinger2_R">
                                        <group name="FKExtraRingFinger2_R">
                                          <group name="FKRingFinger2_R">
                                            <group name="FKXRingFinger2_R">
                                              <group name="FKOffsetRingFinger3_R" position={[-0.013, 0, 0]} rotation={[-0.055, 0.566, -0.126]}>
                                                <group name="SDKFKRingFinger3_R">
                                                  <group name="FKExtraRingFinger3_R">
                                                    <group name="FKRingFinger3_R">
                                                      <group name="FKXRingFinger3_R" />
                                                    </group>
                                                  </group>
                                                </group>
                                              </group>
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetIndexFinger1_R" position={[-0.056, 0.012, 0.001]} rotation={[-0.031, -0.077, -0.103]}>
                  <group name="SDKFKIndexFinger1_R">
                    <group name="FKExtraIndexFinger1_R">
                      <group name="FKIndexFinger1_R">
                        <group name="FKXIndexFinger1_R">
                          <group name="FKOffsetIndexFinger2_R" position={[-0.016, 0, 0]} rotation={[0.06, 0.425, 0.063]}>
                            <group name="SDKFKIndexFinger2_R">
                              <group name="FKExtraIndexFinger2_R">
                                <group name="FKIndexFinger2_R">
                                  <group name="FKXIndexFinger2_R">
                                    <group name="FKOffsetIndexFinger3_R" position={[-0.015, 0, 0]} rotation={[0.064, 0.18, 0.081]}>
                                      <group name="SDKFKIndexFinger3_R">
                                        <group name="FKExtraIndexFinger3_R">
                                          <group name="FKIndexFinger3_R">
                                            <group name="FKXIndexFinger3_R" />
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetMiddleFinger1_R" position={[-0.055, 0, 0]} rotation={[-0.013, 0.244, 0.059]}>
                  <group name="SDKFKMiddleFinger1_R">
                    <group name="FKExtraMiddleFinger1_R">
                      <group name="FKMiddleFinger1_R">
                        <group name="FKXMiddleFinger1_R">
                          <group name="FKOffsetMiddleFinger2_R" position={[-0.016, 0, 0]} rotation={[-0.001, 0.256, 0]}>
                            <group name="SDKFKMiddleFinger2_R">
                              <group name="FKExtraMiddleFinger2_R">
                                <group name="FKMiddleFinger2_R">
                                  <group name="FKXMiddleFinger2_R">
                                    <group name="FKOffsetMiddleFinger3_R" position={[-0.015, 0, 0]} rotation={[-0.001, 0.183, 0]}>
                                      <group name="SDKFKMiddleFinger3_R">
                                        <group name="FKExtraMiddleFinger3_R">
                                          <group name="FKMiddleFinger3_R">
                                            <group name="FKXMiddleFinger3_R" />
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="FKOffsetThumbFinger1_R" position={[-0.01, 0.007, 0.005]} rotation={[1.001, -0.208, -0.612]}>
                  <group name="FKExtraThumbFinger1_R">
                    <group name="FKThumbFinger1_R">
                      <group name="FKXThumbFinger1_R">
                        <group name="FKOffsetThumbFinger2_R" position={[-0.025, 0, 0]} rotation={[0, 0.18, -0.186]}>
                          <group name="SDKFKThumbFinger2_R">
                            <group name="FKExtraThumbFinger2_R">
                              <group name="FKThumbFinger2_R">
                                <group name="FKXThumbFinger2_R">
                                  <group name="FKOffsetThumbFinger3_R" position={[-0.017, 0, 0]} rotation={[-0.029, 0.153, 0.063]}>
                                    <group name="SDKFKThumbFinger3_R">
                                      <group name="FKExtraThumbFinger3_R">
                                        <group name="FKThumbFinger3_R">
                                          <group name="FKXThumbFinger3_R" />
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
            <group name="IKSystem">
              <group name="IKCurve">
                <group name="IKSpineCurve_M" />
              </group>
              <group name="IKHandle">
                <group name="IKHandleFollowMain">
                  <group name="IKcvOffsetSpine1_M" position={[0, 0.541, -0.009]}>
                    <group name="IKcvExtraSpine1_M">
                      <group name="IKcvSpine1_M">
                        <group name="IKSpineLocator1_M" />
                      </group>
                    </group>
                  </group>
                  <group name="IKcvOffsetSpine2_M" position={[0, 0.578, -0.005]}>
                    <group name="IKcvExtraSpine2_M">
                      <group name="IKcvSpine2_M">
                        <group name="IKSpineLocator2_M" />
                      </group>
                    </group>
                  </group>
                  <group name="IKOffsetArm_L" position={[-0.269, 0.547, -0.025]}>
                    <group name="IKExtraArm_L">
                      <group name="IKArm_L">
                        <group name="IKFKAlignedOffsetArm_L" rotation={[-1.828, -0.617, 2.592]}>
                          <group name="IKFKAlignedArm_L" />
                        </group>
                        <group name="IKmessureConstrainToArm_L" />
                      </group>
                    </group>
                  </group>
                  <group name="IKOffsetArm_R" position={[0.269, 0.547, -0.025]}>
                    <group name="IKExtraArm_R">
                      <group name="IKArm_R">
                        <group name="IKFKAlignedOffsetArm_R" rotation={[1.313, -0.617, 2.592]}>
                          <group name="IKFKAlignedArm_R" />
                        </group>
                        <group name="IKmessureConstrainToArm_R" />
                      </group>
                    </group>
                  </group>
                  <group name="IKOffsetConstrainedSpine1_M" position={[0, 0.504, -0.013]}>
                    <group name="IKhybridOffsetSpine1_M" rotation={[-1.465, 1.571, 0]}>
                      <group name="IKhybridFollowSpine1_M">
                        <group name="IKhybridExtraSpine1_M">
                          <group name="IKhybridSpine1_M">
                            <group name="IKhybridOffsetSpine2_M" position={[-0.055, 0, 0]}>
                              <group name="IKhybridExtraSpine2_M">
                                <group name="IKhybridSpine2_M">
                                  <group name="IKhybridOffsetSpine3_M" position={[-0.055, 0, 0]}>
                                    <group name="IKhybridExtraSpine3_M">
                                      <group name="IKhybridSpine3_M">
                                        <group name="IKOffsetSpine3_M" rotation={[Math.PI / 2, -0.106, Math.PI / 2]}>
                                          <group name="IKExtraSpine3_M">
                                            <group name="IKSpine3_M">
                                              <group name="IKSpine3LocalOrient1_M" rotation={[-1.567, 1.571, 0]}>
                                                <group name="IKSpine3LocalOrient2_M" />
                                              </group>
                                              <group name="IKSpineLocator3_M" />
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                      <group name="IKOffsetSpine1_M" rotation={[Math.PI / 2, -0.106, Math.PI / 2]}>
                        <group name="IKExtraSpine1_M">
                          <group name="IKSpine1_M">
                            <group name="IKSpine1LocalOrient1_M" rotation={[-1.465, 1.571, 0]}>
                              <group name="IKSpine1LocalOrient2_M" />
                            </group>
                            <group name="IKSpineLocator0_M" />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="IKOffsetSpine2_M" position={[0, 0.559, -0.007]}>
                    <group name="IKExtraSpine2_M">
                      <group name="IKSpine2_M">
                        <group name="IKSpine2LocalOrient1_M" rotation={[-1.465, 1.571, 0]}>
                          <group name="IKSpine2LocalOrient2_M" />
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="PoleOffsetArm_L" position={[-0.205, 0.563, 0.215]}>
                    <group name="PoleExtraArm_L">
                      <group name="PoleArm_L" />
                    </group>
                  </group>
                  <group name="PoleOffsetArm_R" position={[0.205, 0.563, 0.215]}>
                    <group name="PoleExtraArm_R">
                      <group name="PoleArm_R" />
                    </group>
                  </group>
                  <group name="PoleOffsetLeg_L" position={[-0.052, 0.226, -0.415]}>
                    <group name="PoleExtraLeg_L">
                      <group name="PoleLeg_L" />
                    </group>
                  </group>
                  <group name="PoleOffsetLeg_R" position={[0.052, 0.226, -0.415]}>
                    <group name="PoleExtraLeg_R">
                      <group name="PoleLeg_R" />
                    </group>
                  </group>
                  <group name="IKOffsetLeg_L" position={[-0.055, 0.045, 0.005]}>
                    <group name="IKExtraLeg_L">
                      <group name="IKLeg_L">
                        <group name="IKFKAlignedOffsetLeg_L" rotation={[0, -1.327, -Math.PI / 2]}>
                          <group name="IKFKAlignedLeg_L" />
                        </group>
                        <group name="RollOffsetHeel_L" position={[0.009, -0.041, 0.031]} rotation={[0, 0.244, 0]}>
                          <group name="RollRollerHeel_L">
                            <group name="RollExtraHeel_L">
                              <group name="RollHeel_L">
                                <group name="RollOffsetToesEnd_L" position={[0, 0.003, -0.128]}>
                                  <group name="RollRollerToesEnd_L">
                                    <group name="RollExtraToesEnd_L">
                                      <group name="RollToesEnd_L">
                                        <group name="RollOffsetToes_L" position={[-0.002, 0.007, 0.038]}>
                                          <group name="RollRollerToes_L">
                                            <group name="RollExtraToes_L">
                                              <group name="RollToes_L">
                                                <group name="IKmessureConstrainToLeg_L" position={[0, 0.031, 0.057]} rotation={[0, -0.244, 0]} />
                                              </group>
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                  <group name="IKOffsetLeg_R" position={[0.055, 0.045, 0.005]}>
                    <group name="IKExtraLeg_R">
                      <group name="IKLeg_R">
                        <group name="IKFKAlignedOffsetLeg_R" rotation={[-Math.PI, -1.327, -Math.PI / 2]}>
                          <group name="IKFKAlignedLeg_R" />
                        </group>
                        <group name="RollOffsetHeel_R" position={[-0.009, -0.041, 0.031]} rotation={[0, -0.244, 0]}>
                          <group name="RollRollerHeel_R">
                            <group name="RollExtraHeel_R">
                              <group name="RollHeel_R">
                                <group name="RollOffsetToesEnd_R" position={[0, 0.003, -0.128]}>
                                  <group name="RollRollerToesEnd_R">
                                    <group name="RollExtraToesEnd_R">
                                      <group name="RollToesEnd_R">
                                        <group name="RollOffsetToes_R" position={[0.002, 0.007, 0.038]}>
                                          <group name="RollRollerToes_R">
                                            <group name="RollExtraToes_R">
                                              <group name="RollToes_R">
                                                <group name="IKmessureConstrainToLeg_R" position={[0, 0.031, 0.057]} rotation={[0, 0.244, 0]} />
                                              </group>
                                            </group>
                                          </group>
                                        </group>
                                      </group>
                                    </group>
                                  </group>
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group name="IKJoints">
                <group name="IKParentConstraintHip_L" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                  <group name="IKMessureFromHip_L" position={[0.048, -0.005, -0.046]} rotation={[-3.141, -0.022, 0.117]} />
                  <group name="IKXOffsetHip_L" position={[0.048, -0.005, -0.046]} rotation={[-3.141, -0.022, 0.117]}>
                    <group name="IKXHip_L">
                      <group name="IKXKnee_L" position={[0.212, 0, 0]} rotation={[0, 0, 0.065]}>
                        <group name="IKXAnkle_L" position={[0.199, 0, 0]} rotation={[-0.24, 0.04, -0.069]}>
                          <group name="IKXToes_L" position={[0.031, -0.057, 0]} rotation={[0.055, -0.025, -1.385]} />
                        </group>
                        <group name="IKX2Knee_L" />
                      </group>
                      <group name="IKX2Hip_L" />
                    </group>
                  </group>
                </group>
                <group name="IKParentConstraintHip_R" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                  <group name="IKMessureFromHip_R" position={[0.048, -0.005, 0.046]} rotation={[3.141, 0.022, -3.024]} />
                  <group name="IKXOffsetHip_R" position={[0.048, -0.005, 0.046]} rotation={[3.141, 0.022, -3.024]}>
                    <group name="IKXHip_R">
                      <group name="IKXKnee_R" position={[-0.212, 0, 0]} rotation={[0, 0, 0.065]}>
                        <group name="IKXAnkle_R" position={[-0.199, 0, 0]} rotation={[-0.24, 0.04, -0.069]}>
                          <group name="IKXToes_R" position={[-0.031, 0.057, 0]} rotation={[0.055, -0.025, -1.385]} />
                        </group>
                        <group name="IKX2Knee_R" />
                      </group>
                      <group name="IKX2Hip_R" />
                    </group>
                  </group>
                </group>
                <group name="IKParentConstraintShoulder_L" position={[0, 0.614, -0.002]} rotation={[-1.567, 1.571, 0]}>
                  <group name="IKMessureFromShoulder_L" position={[-0.06, -0.01, -0.085]} rotation={[2.973, -0.943, -0.131]} />
                  <group name="IKXOffsetShoulder_L" position={[-0.06, -0.01, -0.085]} rotation={[2.973, -0.943, -0.131]}>
                    <group name="IKXShoulder_L">
                      <group name="IKXElbow_L" position={[0.127, 0, 0]} rotation={[0, 0, -0.347]}>
                        <group name="IKXWrist_L" position={[0.102, 0, 0]} rotation={[0.29, 0.114, -0.073]}>
                          <group name="IKX2Wrist_L" />
                        </group>
                        <group name="IKX2Elbow_L" />
                      </group>
                      <group name="IKX2Shoulder_L" />
                    </group>
                  </group>
                </group>
                <group name="IKParentConstraintShoulder_R" position={[0, 0.614, -0.002]} rotation={[-1.567, 1.571, 0]}>
                  <group name="IKMessureFromShoulder_R" position={[-0.06, -0.01, 0.085]} rotation={[-2.973, 0.943, 3.01]} />
                  <group name="IKXOffsetShoulder_R" position={[-0.06, -0.01, 0.085]} rotation={[-2.973, 0.943, 3.01]}>
                    <group name="IKXShoulder_R">
                      <group name="IKXElbow_R" position={[-0.127, 0, 0]} rotation={[0, 0, -0.347]}>
                        <group name="IKXWrist_R" position={[-0.102, 0, 0]} rotation={[0.29, 0.114, -0.073]}>
                          <group name="IKX2Wrist_R" />
                        </group>
                        <group name="IKX2Elbow_R" />
                      </group>
                      <group name="IKX2Shoulder_R" />
                    </group>
                  </group>
                </group>
                <group name="IKAcSpineOffset2_M" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                  <group name="IKAcRootPart1FollowOffset_M" position={[-0.037, 0, 0]} />
                  <group name="IKAcRootPart2FollowOffset_M" position={[-0.074, 0, 0]} />
                </group>
                <group name="IKAcSpineOffset3_M">
                  <group name="IKAcPociXformRootPart1_M" position={[0, 0.541, -0.009]} />
                  <group name="IKAcPociXformRootPart2_M" position={[0, 0.578, -0.005]} />
                </group>
                <group name="IKAcSpineOffset_M" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                  <group name="IKAcRootPart1_M" position={[-0.037, 0, 0]}>
                    <group name="IKAcRootPart1_M_tangentConstraint1" />
                  </group>
                  <group name="IKAcRootPart2_M" position={[-0.074, 0, 0]}>
                    <group name="IKAcRootPart2_M_tangentConstraint1" />
                  </group>
                </group>
                <group name="IKParentConstraintRoot_M" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                  <group name="IKfake0Spine_M">
                    <group name="IKFixedOrientRoot_M">
                      <group name="IKAcRootFollowOffset_M" />
                      <group name="IKSpRootFollowOffset_M" />
                    </group>
                    <group name="IKSpRootPart1_M" position={[-0.037, 0, 0]}>
                      <group name="IKSpRootPart2_M" position={[-0.037, 0, 0]}>
                        <group name="IKSpChest_M" position={[-0.037, 0, 0]} />
                      </group>
                    </group>
                  </group>
                  <group name="IKXOffsetRoot_M">
                    <group name="IKXRoot_M">
                      <group name="IKXRootPart1_M" position={[-0.037, 0, 0]}>
                        <group name="IKXRootPart2_M" position={[-0.037, 0, 0]}>
                          <group name="IKXChest_M" position={[-0.037, 0, 0]} rotation={[0, 0, -0.103]} />
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group name="IKSpSpineOffset_M" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                  <group name="IKSpChestFollowOffset_M" position={[-0.111, 0, 0]} rotation={[0, 0, -0.103]} />
                  <group name="IKSpRootPart1FollowOffset_M" position={[-0.037, 0, 0]} />
                  <group name="IKSpRootPart2FollowOffset_M" position={[-0.074, 0, 0]} />
                </group>
              </group>
              <group name="IKMessure">
                <group name="IKmessureLoc1Arm_L" position={[-0.085, 0.675, 0.009]}>
                  <group name="IKmessureLoc2Arm_L" position={[-0.184, -0.127, -0.034]} />
                </group>
                <group name="IKmessureLoc1Arm_R" position={[0.085, 0.675, 0.009]}>
                  <group name="IKmessureLoc2Arm_R" position={[0.184, -0.127, -0.034]} />
                </group>
                <group name="IKmessureLoc1Leg_L" position={[-0.046, 0.456, -0.013]}>
                  <group name="IKmessureLoc2Leg_L" position={[-0.009, -0.41, 0.018]} />
                </group>
                <group name="IKmessureLoc1Leg_R" position={[0.046, 0.456, -0.013]}>
                  <group name="IKmessureLoc2Leg_R" position={[0.009, -0.41, 0.018]} />
                </group>
                <group name="IKdistanceArm_L" />
                <group name="IKdistanceArm_R" />
                <group name="IKdistanceLeg_L" />
                <group name="IKdistanceLeg_R" />
              </group>
              <group name="IKScaler">
                <group name="IKScalerChest_M" />
                <group name="IKScalerRoot_M" />
                <group name="IKScalerRootPart1_M" />
                <group name="IKScalerRootPart2_M" />
              </group>
            </group>
            <group name="RootSystem">
              <group name="RootCenterBtwLegsBlended_M" position={[0, 0.504, -0.013]}>
                <group name="RootOffsetX_M">
                  <group name="RootExtraX_M">
                    <group name="RootX_M" />
                  </group>
                </group>
              </group>
            </group>
            <group name="TwistSystem">
              <group name="FKIKMixElbow_L" position={[-0.189, 0.6, 0.009]} />
              <group name="FKIKMixElbow_R" position={[0.189, 0.6, 0.009]} />
              <group name="FKIKMixKnee_L" position={[-0.051, 0.244, -0.011]} />
              <group name="FKIKMixKnee_R" position={[0.051, 0.244, -0.011]} />
              <group name="FKIKMixWrist_L" position={[-0.269, 0.547, -0.025]} />
              <group name="FKIKMixWrist_R" position={[0.269, 0.547, -0.025]} />
              <group name="TwistFollowParentOffsetElbow_L" position={[-0.085, 0.675, 0.009]} rotation={[-1.446, -0.617, -3.065]}>
                <group name="TwistFollowParentElbow_L">
                  <group name="UnTwistElbow_L" position={[0.127, 0, 0]} rotation={[0, 0, -0.347]}>
                    <group name="TwistBalancerElbow_L" />
                    <group name="TwisterElbow_L" />
                    <group name="TwisterElbowPart1_L" />
                    <group name="TwisterElbowPart2_L" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetElbow_R" position={[0.085, 0.675, 0.009]} rotation={[1.696, -0.617, -3.065]}>
                <group name="TwistFollowParentElbow_R">
                  <group name="UnTwistElbow_R" position={[-0.127, 0, 0]} rotation={[0, 0, -0.347]}>
                    <group name="TwistBalancerElbow_R" />
                    <group name="TwisterElbow_R" />
                    <group name="TwisterElbowPart1_R" />
                    <group name="TwisterElbowPart2_R" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetHip_L" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                <group name="TwistFollowParentHip_L">
                  <group name="UnTwistHip_L" position={[0.048, -0.005, -0.046]} rotation={[-3.141, -0.022, 0.117]}>
                    <group name="TwistBalancerHip_L" />
                    <group name="TwisterHip_L" />
                    <group name="TwisterHipPart1_L" />
                    <group name="TwisterHipPart2_L" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetHip_R" position={[0, 0.504, -0.013]} rotation={[-1.465, 1.571, 0]}>
                <group name="TwistFollowParentHip_R">
                  <group name="UnTwistHip_R" position={[0.048, -0.005, 0.046]} rotation={[3.141, 0.022, -3.024]}>
                    <group name="TwistBalancerHip_R" />
                    <group name="TwisterHip_R" />
                    <group name="TwisterHipPart1_R" />
                    <group name="TwisterHipPart2_R" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetKnee_L" position={[-0.046, 0.456, -0.013]} rotation={[-1.48, -1.548, -3.04]}>
                <group name="TwistFollowParentKnee_L">
                  <group name="UnTwistKnee_L" position={[0.212, 0, 0]} rotation={[0, 0, 0.065]}>
                    <group name="TwistBalancerKnee_L" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetKnee_R" position={[0.046, 0.456, -0.013]} rotation={[1.661, -1.548, -3.04]}>
                <group name="TwistFollowParentKnee_R">
                  <group name="UnTwistKnee_R" position={[-0.212, 0, 0]} rotation={[0, 0, 0.065]}>
                    <group name="TwistBalancerKnee_R" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetShoulder_L" position={[0, 0.614, -0.002]} rotation={[-1.567, 1.571, 0]}>
                <group name="TwistFollowParentShoulder_L">
                  <group name="UnTwistShoulder_L" position={[-0.06, -0.01, -0.085]} rotation={[2.973, -0.943, -0.131]}>
                    <group name="TwistBalancerShoulder_L" />
                    <group name="TwisterShoulder_L" />
                    <group name="TwisterShoulderPart1_L" />
                    <group name="TwisterShoulderPart2_L" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetShoulder_R" position={[0, 0.614, -0.002]} rotation={[-1.567, 1.571, 0]}>
                <group name="TwistFollowParentShoulder_R">
                  <group name="UnTwistShoulder_R" position={[-0.06, -0.01, 0.085]} rotation={[-2.973, 0.943, 3.01]}>
                    <group name="TwistBalancerShoulder_R" />
                    <group name="TwisterShoulder_R" />
                    <group name="TwisterShoulderPart1_R" />
                    <group name="TwisterShoulderPart2_R" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetWrist_L" position={[-0.189, 0.6, 0.009]} rotation={[-1.446, -0.617, 2.871]}>
                <group name="TwistFollowParentWrist_L">
                  <group name="UnTwistWrist_L" position={[0.102, 0, 0]} rotation={[0.29, 0.114, -0.073]}>
                    <group name="TwistBalancerWrist_L" />
                  </group>
                </group>
              </group>
              <group name="TwistFollowParentOffsetWrist_R" position={[0.189, 0.6, 0.009]} rotation={[1.696, -0.617, 2.871]}>
                <group name="TwistFollowParentWrist_R">
                  <group name="UnTwistWrist_R" position={[-0.102, 0, 0]} rotation={[0.29, 0.114, -0.073]}>
                    <group name="TwistBalancerWrist_R" />
                  </group>
                </group>
              </group>
            </group>
            <group name="ConstraintSystem" />
            <group name="MainSystem">
              <group name="Main" />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./assets/Gaudi.gltf')

export default Gaudi